version: '3.8'

services:
  web:
    build: 
      context: ./src
      dockerfile: Dockerfile.prod
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000 --log-level=debug
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - log_volume:/home/app/web/logs
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  log_volume: