version: '3.8'

services:
  web:
    build: 
      context: ./src
      dockerfile: Dockerfile.sqlite
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.sqlite

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: