# Generated by Django 4.1.2 on 2022-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_item_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
