# Generated by Django 4.1.2 on 2022-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_item_image_alter_item_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="items/files/pictures"
            ),
        ),
    ]
