# Generated by Django 4.1.2 on 2022-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="items/static/images"
            ),
        ),
    ]
